# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AJ Zane's Dev Log
email: androiddreams@AJZane.com.com
description: > # this means to ignore newlines until "baseurl:"
  I'm AJ Zane. I do web stuff. This is where I log my development experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://azanebrain.github.io" # the base hostname & protocol for your site
twitter_username: azanebrain
github_username:  azanebrain
permalink:        /news/:title/

# Build settings
markdown: kramdown
